### ISSUE TITLE
Struggling with `gradle clean lessCompile`

### ISSUE THREAD

**Issue by nkiesel** [voplex95/gradle-lesscompiler-plugin#2]
Hi,

using version 1.0.2 (thanks for merging and releasing!).

`gradle clean` followed by `gradle lessCompile` now works for me.  However, running `gradle clean lessCompile` fails with `java.io.FileNotFoundException`.  Adding some simple println logging shows that the `lessCompile` closure (where I define `target` and create it) is executed before the `clean`.  Thus, `clean` wipes out the target directory before the actual `lessCompile`.  My current configuration is

```
lessCompile {
	source = file('less/msi.less')
	target = file('gbuild/css')
	target.mkdirs()
}
```

What am I doing wrong?  Can I somehow split the configuration from the invocation?

**Comment by voplex95** [comment]
@nkiesel, I believe ```mustRunAfter``` rule will solve this problem. I am going to release fix for this soon.

Info related to ```mustRunAfter``` rule:
https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:ordering_tasks

**Comment by nkiesel** [comment]
Tried adding `mustRunAfter` (actually tried before but just repeated to make sure), but that results in an exception:
```
lt-nkiesel:~trunk(lessc)% gradle lessCompile                       
FAILURE: Build failed with an exception.

* Where:
Build file '/home/nkiesel/work/Platform/trunk/modules/ui/build.gradle' line: 71

* What went wrong:
A problem occurred evaluating project ':modules:ui'.
> Could not get unknown property 'clean' for project ':modules:ui' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.192 secs
lt-nkiesel:~trunk(lessc)% cat -n modules/ui/build.gradle|grep -w 71
    71	lessCompile.mustRunAfter clean
```

**Comment by nkiesel** [comment]
Seems that with v1.0.3 no longer requiring the `target.mkdirs()` my problem disappeared.  I guess the configuration is evaluated before `clean` is run, so `clean` removed the target directory again.  v1.0.3 runs this mkdirs during processing time, thus avoiding this problem.

One lesson learned is that although Gradle allows to add arbitrary code to that configuration block, this is not recommended.

**Comment by voplex95** [comment]
@nkiesel, glad to know it helped
